#
# Definition of all trackable objects
# Identifier corresponds to Streaming ID set in Motive
#

vrpn_mocap/client:
    ros__parameters:
        server: 192.168.0.127
        port: 3883
        frame_id: world
        update_freq: 100.0
        refresh_freq: 1.0
        multi_sensor: false
